### PR TITLE
Feature/add search

### PR DESCRIPTION
**Pull request by s-pace**
Add [DocSearch](https://community.algolia.com/docsearch/) search to the course.

### CODE REVIEW

**Review by adrienjoly — APPROVED** [review]
LGTM

Thank you Sylvain, you rock! 🙌

**Comment by adrienjoly** [comment]
Aren't we supposed to display the Algolia logo, though?

**Comment by s-pace** [comment]
You do but you are. It is inside the footer of the dropdown.

You are welcome :)

**Comment by s-pace** [comment]
image

**Comment by adrienjoly** [comment]
Oh indeed! That's quite subtle :-)

Thank you very much, Sylvain!

**Pull request merged**
